version: '3'
services:
  web:
    build: ./frontend-portal
    ports:
      - "4000:4000"
  mysql:
    image: jhonpaco/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: mysql
    ports:
      - "3306:3306"
  brokerdotnet:
    build: ./MyBroker2DotNet
    ports:
      - "8080:8080"
